import Head from "next/head";
import { Button, Container } from "@mui/material";
import Typography from "@mui/material/Typography";
import Link from "next/link";

const Home = () => {
  return (
    <>
      <Head>
        <title>Главное меню</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="d-flex align-items-center bg-secondary">
        <Typography
          variant="h1"
          className="fs-1 fw-bold p-3 bg-secondary text-bg-info"
        >
          <Link href="/">Turbo-Sapr</Link>
        </Typography>
        <Typography variant="h2" className="ms-5 fs-3 text-info">
          Главное меню
        </Typography>
      </header>
      <main>
        <Container maxWidth="xs">
          <div className="d-flex flex-column">
            <Link className="w-100" href="/preprocessor">
              <Button variant="contained" className="w-100 m-3 py-3">
                Препроцессор
              </Button>
            </Link>
            <Link href="/postprocessor">
              <Button variant="contained" className="w-100 m-3 py-3">
                Постпроцессор
              </Button>
            </Link>
          </div>
        </Container>
      </main>
    </>
  );
};

export default Home;
